version: '3.9'

services:
  server:
    container_name: aldebaran 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env

  postgres:
    container_name: aldebaran-db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
